name: Deploy to Moon Server

on:
  push:
    branches:
      - stage

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Deploy to server
      uses: appleboy/scp-action@master
      with:
        host: moon.scs.torontomu.ca
        username: avm
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: index.html
        target: /home/avm/courses/cps847/<your_scs_id>
